# Generated by Django 4.2.1 on 2023-05-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_id', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_district',
            },
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_id', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_state',
            },
        ),
    ]
