# Generated by Django 4.2.1 on 2023-05-06 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger_app', '0002_district_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='charging_station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_id', models.IntegerField()),
                ('place', models.CharField(max_length=50, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'tbl_charging_station',
            },
        ),
    ]
