# Generated by Django 4.2.1 on 2023-05-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger_app', '0003_charging_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_subject', models.CharField(max_length=50)),
                ('complaint', models.CharField(max_length=150)),
                ('user_login_id', models.IntegerField()),
                ('reply', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_complaint',
            },
        ),
    ]
