# Generated by Django 4.2.1 on 2023-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger_app', '0004_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('enquiry_subject', models.CharField(max_length=50)),
                ('enquiry', models.CharField(max_length=150)),
                ('user_login_id', models.IntegerField()),
                ('reply', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_enquiry',
            },
        ),
    ]
