# Generated by Django 4.2.1 on 2023-05-20 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger_app', '0005_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='charger_station_booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('user_login_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('station_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_booking',
            },
        ),
    ]
