# Generated by Django 4.2.1 on 2023-05-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger_app', '0006_charger_station_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fee', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_fee',
            },
        ),
    ]
